import turtle
turtle.Screen()
turtle.setup(800,600)
turtle.title('거북이등산')
turtle.bgpic('산길.gif')
turtle.Turtle()
turtle.shape('turtle')
turtle.penup()
turtle.goto(-100,-250)
turtle.left(30)
turtle.forward(200)
turtle.setheading(90)
turtle.forward(10)
turtle.setheading(150)
turtle.forward(100)
input()